Repository erikrobstad/sdk-nrf, pull requests merged in 2022-07, with the labels that each got.

#21 Oct 2141 refactor configs to fit bap
  applications/nrf5340_audio/Kconfig
  applications/nrf5340_audio/Kconfig.defaults
  applications/nrf5340_audio/overlay-debug.conf
  applications/nrf5340_audio/overlay-gateway.conf
  applications/nrf5340_audio/overlay-headset.conf
  applications/nrf5340_audio/overlay-release.conf
  applications/nrf5340_audio/prj.conf
  applications/nrf5340_audio/prj_release.conf
  applications/nrf5340_audio/src/audio/Kconfig
  applications/nrf5340_audio/src/audio/Kconfig.defaults
  applications/nrf5340_audio/src/bluetooth/CMakeLists.txt
  applications/nrf5340_audio/src/bluetooth/Kconfig
  applications/nrf5340_audio/src/bluetooth/Kconfig.defaults
  applications/nrf5340_audio/src/bluetooth/le_audio_bis_gateway.c
  applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c
  applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
  applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
  applications/nrf5340_audio/src/modules/Kconfig
  applications/nrf5340_audio/src/modules/Kconfig.defaults
  applications/nrf5340_audio/src/utils/Kconfig
  applications/nrf5340_audio/src/utils/Kconfig.defaults
  applications/nrf5340_audio/tools/buildprog/buildprog.py
Labels: changelog-entry-required

#20 applications: nrf5340_audio: Re-introduce VCS in BAP implementation
  applications/nrf5340_audio/src/bluetooth/Kconfig.defaults
  applications/nrf5340_audio/src/bluetooth/ble_audio_services.c
  applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
  applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
Labels: changelog-entry-required

#19 applications: nrf5340_audio: Stop aborting encoder thread on pause
  applications/nrf5340_audio/src/audio/audio_system.c
  applications/nrf5340_audio/src/bluetooth/le_audio_bis_gateway.c
  applications/nrf5340_audio/src/utils/data_fifo.c
  applications/nrf5340_audio/src/utils/data_fifo.h
Labels: changelog-entry-required

#25 applications: nrf5340_audio: Change DRFT_STATE to DRIFT_STATE
  applications/nrf5340_audio/src/audio/audio_datapath.c
Labels: changelog-entry-required

#28 applications: nrf5340_audio: Fix BIS issue after upmerge
  applications/nrf5340_audio/src/bluetooth/le_audio_bis_gateway.c
  applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c
Labels: changelog-entry-required

#29 applications: nrf5340_audio: Set pres delay based on QoS settings
  applications/nrf5340_audio/src/audio/audio_datapath.c
  applications/nrf5340_audio/src/audio/audio_datapath.h
  applications/nrf5340_audio/src/audio/audio_system.c
  applications/nrf5340_audio/src/audio/audio_system.h
  applications/nrf5340_audio/src/audio/sw_codec_select.h
  applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
  applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
Labels: changelog-entry-required

#26 applications: nrf5340_audio: Fix drift compensation not locking
  applications/nrf5340_audio/src/audio/audio_datapath.c
Labels: changelog-entry-required

#27 OCT-NONE-fix-cis-issue-after-zephyr-updated
  applications/nrf5340_audio/src/bluetooth/Kconfig.defaults
  applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
Labels: changelog-entry-required

#31 applications: nrf5340_audio: Set SDU size based on bitrate
  applications/nrf5340_audio/src/audio/Kconfig
  applications/nrf5340_audio/src/audio/audio_system.c
  applications/nrf5340_audio/src/audio/sw_codec_select.h
  applications/nrf5340_audio/src/bluetooth/Kconfig.defaults
  applications/nrf5340_audio/src/bluetooth/le_audio.h
  applications/nrf5340_audio/src/bluetooth/le_audio_bis_gateway.c
  applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c
  applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
  applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
Labels: changelog-entry-required

#33 applications: nrf5340_audio: Fixed the name of CIS gateway preset
  applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
Labels: changelog-entry-required

#35 applications: nrf5340_audio: Run clang-format on all application files
  applications/nrf5340_audio/src/audio/audio_datapath.c
  applications/nrf5340_audio/src/audio/sw_codec_select.c
  applications/nrf5340_audio/src/modules/audio_i2s.c
  applications/nrf5340_audio/src/modules/led.c
Labels: changelog-entry-required

#24 applications: nrf5340_audio: Implement stereo BIS
  applications/nrf5340_audio/src/audio/audio_system.c
  applications/nrf5340_audio/src/bluetooth/Kconfig.defaults
  applications/nrf5340_audio/src/bluetooth/le_audio_bis_gateway.c
  applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c
Labels: changelog-entry-required

#38 applications: nrf5340_audio: Add back if TRANSPORT_CIS
  applications/nrf5340_audio/src/bluetooth/Kconfig.defaults
Labels: changelog-entry-required

#34 applications: nrf5340_audio: Add dual CIS link feature
  applications/nrf5340_audio/Kconfig.defaults
  applications/nrf5340_audio/src/audio/audio_datapath.c
  applications/nrf5340_audio/src/audio/sw_codec_select.h
  applications/nrf5340_audio/src/bluetooth/Kconfig
  applications/nrf5340_audio/src/bluetooth/Kconfig.defaults
  applications/nrf5340_audio/src/bluetooth/le_audio.h
  applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
  applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
  applications/nrf5340_audio/src/utils/pcm_stream_channel_modifier.c
  applications/nrf5340_audio/src/utils/pcm_stream_channel_modifier.h
Labels: changelog-entry-required

#41 applications: nrf5340_audio: Get location from PACS
  applications/nrf5340_audio/src/bluetooth/le_audio.h
  applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
  applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
  west.yml
Labels: changelog-entry-required, manifest

#39 applications: nrf5340_audio: Remove support for SBC
  applications/nrf5340_audio/CMakeLists.txt
  applications/nrf5340_audio/README.rst
  applications/nrf5340_audio/src/audio/Kconfig
  applications/nrf5340_audio/src/audio/audio_system.c
  applications/nrf5340_audio/src/audio/sw_codec_select.c
  applications/nrf5340_audio/src/audio/sw_codec_select.h
  applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
  ext/CMakeLists.txt
  ext/Kconfig
  ext/sbc/CMakeLists.txt
  ext/sbc/Kconfig
  ext/sbc/decoder/include/oi_assert.h
  ext/sbc/decoder/include/oi_bitstream.h
  ext/sbc/decoder/include/oi_bt_spec.h
  ext/sbc/decoder/include/oi_codec_sbc.h
  ext/sbc/decoder/include/oi_codec_sbc_private.h
  ext/sbc/decoder/include/oi_common.h
  ext/sbc/decoder/include/oi_cpu_dep.h
  ext/sbc/decoder/include/oi_modules.h
  ext/sbc/decoder/include/oi_osinterface.h
  ext/sbc/decoder/include/oi_status.h
  ext/sbc/decoder/include/oi_stddefs.h
  ext/sbc/decoder/include/oi_string.h
  ext/sbc/decoder/include/oi_time.h
  ext/sbc/decoder/include/oi_utils.h
  ext/sbc/decoder/srce/alloc.c
  ext/sbc/decoder/srce/bitalloc-sbc.c
  ext/sbc/decoder/srce/bitalloc.c
  ext/sbc/decoder/srce/bitstream-decode.c
  ext/sbc/decoder/srce/decoder-oina.c
  ext/sbc/decoder/srce/decoder-private.c
  ext/sbc/decoder/srce/decoder-sbc.c
  ext/sbc/decoder/srce/dequant.c
  ext/sbc/decoder/srce/framing-sbc.c
  ext/sbc/decoder/srce/framing.c
  ext/sbc/decoder/srce/oi_codec_version.c
  ext/sbc/decoder/srce/readsamplesjoint.inc
  ext/sbc/decoder/srce/synthesis-8-generated.c
  ext/sbc/decoder/srce/synthesis-dct8.c
  ext/sbc/decoder/srce/synthesis-sbc.c
  ext/sbc/encoder/include/sbc_dct.h
  ext/sbc/encoder/include/sbc_enc_func_declare.h
  ext/sbc/encoder/include/sbc_encoder.h
  ext/sbc/encoder/include/sbc_types.h
  ext/sbc/encoder/srce/sbc_analysis.c
  ext/sbc/encoder/srce/sbc_dct.c
  ext/sbc/encoder/srce/sbc_dct_coeffs.c
  ext/sbc/encoder/srce/sbc_enc_bit_alloc_mono.c
  ext/sbc/encoder/srce/sbc_enc_bit_alloc_ste.c
  ext/sbc/encoder/srce/sbc_enc_coeffs.c
  ext/sbc/encoder/srce/sbc_encoder.c
  ext/sbc/encoder/srce/sbc_packing.c
Labels: changelog-entry-required, doc-required

#37 applications: nrf5340_audio: Add bonding
  applications/nrf5340_audio/src/bluetooth/Kconfig.defaults
  applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
  applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
  applications/nrf5340_audio/src/main.c
Labels: changelog-entry-required
